version: "3"
services:    
  web1:
    image: nginx:alpine
    container_name: web1
    ports:
      - 5000:80
    volumes:
      - ./config/templates/web1.html:/usr/share/nginx/html/index.html

  web2:
    image: nginx:alpine
    container_name: web2
    ports:
      - 5001:80
    volumes:
      - ./config/templates/web2.html:/usr/share/nginx/html/index.html

  reverse_proxy:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - 80:80
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf